::fk::举个例子: AutoHotkey 真是好用到爆!!!!! 强烈安利..... 嘤嘤嘤 ~ ~ ~
::boo::border: red solid 1px;
::bbb::background-color: pink;
::conso::console.log();
::posiab::position:absolute;
::posire::position:relative;
::whbg::width: 150px; height: 150px; background-color: skyblue;
::htmllll::<html lang="zh"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta http-equiv="X-UA-Compatible" content="ie=edge"><title>YXB</title><style>*{margin:0;padding:0;text-decoration:none;list-style-type:none}body{max-width:640px;min-width:320px;border:red solid 1px}</style><link rel="styleSheet" href="" type="text/css"><script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script></head><body><h1>YXB</h1></body><script type="text/javascript" src=""></script></html>
::maxmin::max-width:640px;min-width:320px;border:green solid 1px;margin:0 auto;
::pause::print("===============================  程序暂停(pause)了  =========================");time.sleep(9999);
::111::```````  `n`n`n```````
::cout::cout << 123 << endl;
::forr::
clipboard=
(
	for (int i = 0; i < 10; i++) {

	}
)
Send ^v{enter}
Sleep, 1000
Return
::vvvdum::
clipboard=
(
var_dump();
die();
)
Send ^v{enter}
Sleep, 1000
Return
::cplus::
clipboard=
(
#include <iostream>
#include<string>
using namespace std;

class example
{

};

void  main()
{

}
)
Send ^v{enter}
Sleep, 1000
Return
::6666::
clipboard=
(
<details>
<summary><b>my_name_is_jack</b></summary>


</details>
)
Send ^v{enter}
Sleep, 1000
Return
^3::send %A_YYYY%-%A_MM%-%A_DD% %A_Hour%:%A_Min%:%A_Sec%